const products = [
  {
    id: "azzaro-most-wanted-intense",
    name: "The Most Wanted Intense",
    brand: "Azzaro",
    sizes: [
      { ml: 5, price: 350 },
      { ml: 10, price: 600 },
    ],
    gender: "Hombre",
    family: "Oriental",
    notesTop: ["Cardamomo", "Jengibre", "Bergamota"],
    notesHeart: ["Cacao", "Canela", "Nuez moscada"],
    notesBase: ["Vainilla", "Ámbar", "Tonka", "Pachulí"],
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=800&fit=crop",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: "jpg-le-beau",
    name: "Le Beau",
    brand: "Jean Paul Gaultier",
    sizes: [
      { ml: 5, price: 320 },
      { ml: 10, price: 550 },
    ],
    gender: "Hombre",
    family: "Acuático",
    notesTop: ["Bergamota", "Coco", "Albaricoque"],
    notesHeart: ["Jazmín", "Ylang-ylang", "Neroli"],
    notesBase: ["Vetiver", "Ámbar", "Musk", "Sándalo"],
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&h=800&fit=crop",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: "pr-invictus-victory-elixir",
    name: "Invictus Victory Elixir",
    brand: "Paco Rabanne",
    sizes: [
      { ml: 5, price: 380 },
      { ml: 10, price: 650 },
    ],
    gender: "Hombre",
    family: "Amaderado",
    notesTop: ["Lavanda", "Bergamota", "Pimienta"],
    notesHeart: ["Vetiver", "Cedro", "Geranio"],
    notesBase: ["Ámbar", "Musk", "Sándalo", "Vainilla"],
    image: "https://images.unsplash.com/photo-1595425970377-c970d8d436e0?w=800&h=800&fit=crop",
    isNew: true,
    isBestSeller: true,
  },
  {
    id: "pr-invictus",
    name: "Invictus",
    brand: "Paco Rabanne",
    sizes: [
      { ml: 5, price: 300 },
      { ml: 10, price: 520 },
    ],
    gender: "Hombre",
    family: "Acuático",
    notesTop: ["Mandarina", "Pomelo", "Hoja de laurel"],
    notesHeart: ["Jazmín", "Neroli", "Salvia"],
    notesBase: ["Ámbar gris", "Musk", "Roble"],
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=800&fit=crop",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: "jpg-le-male-parfum",
    name: "Le Male Le Parfum",
    brand: "Jean Paul Gaultier",
    sizes: [
      { ml: 5, price: 340 },
      { ml: 10, price: 580 },
    ],
    gender: "Hombre",
    family: "Oriental",
    notesTop: ["Cardamomo", "Bergamota", "Lavanda"],
    notesHeart: ["Iris", "Violeta", "Especias"],
    notesBase: ["Vainilla", "Ámbar", "Tonka", "Musk"],
    image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&h=800&fit=crop",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: "pr-1million-royale",
    name: "1 Million Royale",
    brand: "Paco Rabanne",
    sizes: [
      { ml: 5, price: 360 },
      { ml: 10, price: 620 },
    ],
    gender: "Hombre",
    family: "Oriental",
    notesTop: ["Rosa", "Azafrán", "Bergamota"],
    notesHeart: ["Miel", "Canela", "Especias"],
    notesBase: ["Ámbar", "Cuero", "Tonka", "Pachulí"],
    image: "https://images.unsplash.com/photo-1595425970377-c970d8d436e0?w=800&h=800&fit=crop",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "nautica-voyage",
    name: "Voyage",
    brand: "Nautica",
    sizes: [
      { ml: 5, price: 180 },
      { ml: 10, price: 320 },
    ],
    gender: "Hombre",
    family: "Acuático",
    notesTop: ["Manzana verde", "Lotus", "Hojas de mimosa"],
    notesHeart: ["Rosa", "Jazmín", "Lirio"],
    notesBase: ["Cedro", "Musk", "Ámbar"],
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&h=800&fit=crop",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "rasasi-hawas",
    name: "Hawas",
    brand: "Rasasi",
    sizes: [
      { ml: 5, price: 280 },
      { ml: 10, price: 480 },
    ],
    gender: "Hombre",
    family: "Acuático",
    notesTop: ["Manzana", "Bergamota", "Lavanda"],
    notesHeart: ["Violeta", "Jazmín", "Neroli"],
    notesBase: ["Ámbar", "Musk", "Sándalo", "Vetiver"],
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=800&fit=crop",
    isNew: false,
    isBestSeller: true,
  },
]

